import type { ProductMock } from "@shared/types/product";

import ProductOne from "@assets/images/product-1.png";
import ProductTwo from "@assets/images/product-2.png";
import ProductThree from "@assets/images/product-3.png";
import ProductFour from "@assets/images/product-4.png";

export const productsMock: ProductMock[] = [
  {
    id: "1",
    title: "Золотая подвеска",
    brand: "Бриллианты Якутии",
    imageUrl: ProductOne,
    imageAlt: "Золотая подвеска",
    price: 250_400,
    discount: 2.694,
    bonuses: 329,
    rating: 4.5,
    reviews: 90,
    inFavorites: false,
    inCart: false,
  },
  {
    id: "2",
    title: "Золотое кольцо с изумрудами",
    brand: "Бриллианты Якутии",
    imageUrl: ProductTwo,
    imageAlt: "Золотое кольцо с изумрудами",
    price: 250_400,
    discount: 2.694,
    bonuses: 329,
    rating: 4.7,
    reviews: 64,
    inFavorites: false,
    inCart: false,
  },
  {
    id: "3",
    title: "Золотое кольцо с бриллиантом",
    brand: "Бриллианты Якутии",
    imageUrl: ProductThree,
    imageAlt: "Золотое кольцо с бриллиантом",
    price: 250_400,
    discount: 19.359,
    bonuses: 420,
    rating: 4.9,
    reviews: 101,
    inFavorites: false,
    inCart: false,
  },
  {
    id: "4",
    title: "Золотое браслет с фианитами",
    brand: "Бриллианты Якутии",
    imageUrl: ProductFour,
    imageAlt: "Золотое браслет с фианитами",
    price: 250_400,
    discount: 2.694,
    bonuses: 329,
    rating: 4.5,
    reviews: 78,
    inFavorites: false,
    inCart: false,
  },
  {
    id: "5",
    title: "Золотое кольцо с изумрудами",
    brand: "Бриллианты Якутии",
    imageUrl: ProductTwo,
    imageAlt: "Золотое кольцо с изумрудами",
    price: 250_400,
    discount: 2.694,
    bonuses: 329,
    rating: 4.7,
    reviews: 64,
    inFavorites: false,
    inCart: false,
  },
  {
    id: "6",
    title: "Золотое кольцо с бриллиантом",
    brand: "Бриллианты Якутии",
    imageUrl: ProductThree,
    imageAlt: "Золотое кольцо с бриллиантом",
    price: 250_400,
    discount: 19.359,
    bonuses: 420,
    rating: 4.9,
    reviews: 101,
    inFavorites: false,
    inCart: false,
  },
];
